# nginx proxy address - http://172.17.0.1:59081

name: umbrel
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: dockurr/umbrel:latest
    container_name: umbrelos-app
    hostname: umbrelos
    restart: always
    pull_policy: always
    tty: true
    stdin_open: true
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: umbrelos-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:59081:80
    volumes:
      - './volumes/data/umbrel:/data:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - umbrel
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://umbrelos-app:80'
      - 'cloudflare.hostname=umbrel.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.umbrelos-app.entrypoints=http'
      - 'traefik.http.routers.umbrelos-app-secure.tls=true'
      - 'traefik.http.routers.umbrelos-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.umbrelos-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.umbrelos-app.middlewares=umbrelos-app-https-redirect'
      - 'traefik.http.routers.umbrelos-app-secure.entrypoints=https'
      - 'traefik.http.routers.umbrelos-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.umbrelos-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.umbrelos-app-secure.service=umbrelos-app'
      - 'traefik.http.services.umbrelos-app.loadbalancer.server.port=80'

networks:
  umbrel:
    name: umbrel
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
